export type ProductCategory =
  | "sunscreen"
  | "cleanser"
  | "moisturizer"
  | "serum_niacinamide"
  | "serum_vitamin_c"
  | "serum_aha_bha"
  | "serum_retinol"
  | "serum_brightening"
  | "toner"
  | "treatment_jerawat";

export type SkinTypeMatch = "normal" | "berminyak" | "kering" | "kombinasi" | "sensitif" | "semua tipe" | "berjerawat";
export type PriceRange = "budget" | "mid" | "premium";

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: ProductCategory;
  emoji: string;

  tagline: string;
  key_ingredients: string[];
  skin_types: SkinTypeMatch[];
  concerns: string[];

  price_min: number;
  price_max: number;
  price_range: PriceRange;

  where_to_buy: string[];
  spf?: number;
  bpom_registered: boolean;

  why_good: string;
  who_should_skip?: string;

  rating_community: number;
}

export const PRODUCTS: Product[] = [
  // ── SUNSCREEN ──────────────────────────────────────
  {
    id: "azarine-hydrasoothe-spf45",
    name: "Hydrasoothe Sunscreen SPF 45 PA+++",
    brand: "Azarine",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Sunscreen terjangkau terbaik Indonesia — tekstur ringan, no white cast",
    key_ingredients: ["Ethylhexyl Methoxycinnamate", "Butyl Methoxydibenzoylmethane", "Niacinamide"],
    skin_types: ["normal", "berminyak", "kombinasi"],
    concerns: ["UV protection", "Penuaan dini", "Hiperpigmentasi"],
    price_min: 30000,
    price_max: 40000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret", "Alfamart"],
    spf: 45,
    bpom_registered: true,
    why_good: "Value terbaik di Indonesia. Teksturnya ringan, cepat meresap, tidak meninggalkan white cast, dan ada niacinamide bonus untuk kontrol minyak.",
    rating_community: 4.6,
  },
  {
    id: "wardah-uv-shield-spf50",
    name: "UV Shield Essential Sunscreen SPF 50 PA+++",
    brand: "Wardah",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Sunscreen everyday yang mudah didapat dan terjangkau",
    key_ingredients: ["Zinc Oxide", "Titanium Dioxide", "Centella Asiatica"],
    skin_types: ["normal", "kering", "sensitif"],
    concerns: ["UV protection", "Kulit sensitif"],
    price_min: 45000,
    price_max: 60000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret", "Alfamart", "Guardian"],
    spf: 50,
    bpom_registered: true,
    why_good: "Mineral sunscreen yang lebih cocok untuk kulit sensitif. Mudah ditemukan di minimarket seluruh Indonesia.",
    rating_community: 4.3,
  },
  {
    id: "skintific-aqua-air-spf50",
    name: "Aqua Air Sunscreen SPF 50 PA++++",
    brand: "Skintific",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Seringan air, perlindungan maksimal",
    key_ingredients: ["Tinosorb S", "Tinosorb M", "Hyaluronic Acid"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["UV protection", "Kulit berminyak", "Pori besar"],
    price_min: 55000,
    price_max: 75000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Official Store"],
    spf: 50,
    bpom_registered: true,
    why_good: "Menggunakan UV filter generasi terbaru (Tinosorb) yang lebih stabil dari chemical filter biasa. Tekstur sangat ringan.",
    rating_community: 4.7,
  },

  // ── CLEANSER ──────────────────────────────────────
  {
    id: "cetaphil-gentle-cleanser",
    name: "Gentle Skin Cleanser",
    brand: "Cetaphil",
    category: "cleanser",
    emoji: "🫧",
    tagline: "Pembersih paling gentle — direkomendasikan dermatologis sejak 1947",
    key_ingredients: ["Glycerin", "Panthenol", "Niacinamide"],
    skin_types: ["kering", "sensitif", "normal"],
    concerns: ["Kulit sensitif", "Skin barrier lemah", "Kulit kering"],
    price_min: 50000,
    price_max: 70000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Guardian", "Watsons", "Apotek"],
    bpom_registered: true,
    why_good: "Tidak ada SLS, tidak ada wewangian, pH rendah. Bisa dipakai untuk wajah dan badan. Standar emas untuk kulit sensitif dan kulit yang sedang dalam recovery.",
    rating_community: 4.8,
  },
  {
    id: "somethinc-low-ph-cleanser",
    name: "Low pH Hello Gentle Cleanser",
    brand: "Somethinc",
    category: "cleanser",
    emoji: "🫧",
    tagline: "Low pH, bebas SLS — sempurna untuk routine exfoliant",
    key_ingredients: ["Centella Asiatica", "Aloe Vera", "PHA"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Jerawat", "Komedo", "Kulit berminyak"],
    price_min: 40000,
    price_max: 55000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "pH rendah penting kalau kamu pakai AHA/BHA — cleanser pH tinggi bisa menonaktifkan exfoliant. Ini solusinya.",
    rating_community: 4.5,
  },
  {
    id: "npure-centella-cleanser",
    name: "Centella Asiatica Cleansing Gel",
    brand: "NPURE",
    category: "cleanser",
    emoji: "🫧",
    tagline: "Cleanser Cica yang bersihkan dan tenangkan sekaligus",
    key_ingredients: ["Centella Asiatica", "Aloe Vera", "Green Tea"],
    skin_types: ["sensitif", "normal", "kombinasi"],
    concerns: ["Kemerahan", "Kulit sensitif", "Jerawat ringan"],
    price_min: 30000,
    price_max: 45000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret"],
    bpom_registered: true,
    why_good: "Centella Asiatica membantu menenangkan kulit setiap kali cuci muka. Budget-friendly dan efektif.",
    rating_community: 4.4,
  },

  // ── MOISTURIZER ──────────────────────────────────────
  {
    id: "cerave-moisturizing-cream",
    name: "Moisturizing Cream",
    brand: "CeraVe",
    category: "moisturizer",
    emoji: "🧴",
    tagline: "Moisturizer dengan 3 ceramide esensial — memperbaiki skin barrier",
    key_ingredients: ["Ceramide NP", "Ceramide AP", "Ceramide EOP", "Hyaluronic Acid", "Niacinamide"],
    skin_types: ["kering", "sensitif", "normal"],
    concerns: ["Skin barrier rusak", "Kulit kering", "Eksim", "Sensitif"],
    price_min: 100000,
    price_max: 150000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Guardian", "Watsons"],
    bpom_registered: true,
    why_good: "Kombinasi 3 ceramide + HA + niacinamide dalam satu produk. Dikembangkan bersama dermatologis. Best in class untuk memperbaiki skin barrier.",
    who_should_skip: "Kulit sangat berminyak (tekstur cream bisa terasa berat)",
    rating_community: 4.9,
  },
  {
    id: "hada-labo-gokujyun",
    name: "Gokujyun Premium Hyaluronic Lotion",
    brand: "Hada Labo",
    category: "moisturizer",
    emoji: "🧴",
    tagline: "5 jenis Hyaluronic Acid — hidrasi terdalam",
    key_ingredients: ["Super Hyaluronic Acid", "Hyaluronic Acid", "Collagen"],
    skin_types: ["kering", "normal", "kombinasi", "berminyak"],
    concerns: ["Dehidrasi", "Kulit kering", "Kulit kusam"],
    price_min: 65000,
    price_max: 90000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Guardian", "Watsons", "Minimarket"],
    bpom_registered: true,
    why_good: "Mengandung 5 ukuran molekul HA yang meresap ke lapisan kulit berbeda. Hasil hidrasi maksimal tanpa rasa berminyak.",
    rating_community: 4.7,
  },
  {
    id: "skintific-5x-ceramide",
    name: "5X Ceramide Barrier Serum",
    brand: "Skintific",
    category: "moisturizer",
    emoji: "🧴",
    tagline: "5 jenis ceramide + niacinamide — repair dan brighten sekaligus",
    key_ingredients: ["Ceramide 5 Complex", "Niacinamide", "Panthenol"],
    skin_types: ["kering", "sensitif", "normal", "kombinasi"],
    concerns: ["Skin barrier lemah", "Bekas jerawat", "Kulit kering sensitif"],
    price_min: 60000,
    price_max: 80000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Versi lokal CeraVe dengan harga lebih terjangkau dan formulasi yang sangat solid. Sangat cocok untuk pemula.",
    rating_community: 4.6,
  },

  // ── SERUM NIACINAMIDE ──────────────────────────────────────
  {
    id: "somethinc-niacinamide",
    name: "Niacinamide + Moisture Beet Serum",
    brand: "Somethinc",
    category: "serum_niacinamide",
    emoji: "✨",
    tagline: "Niacinamide 10% + hidrasi tahan lama — kontrol minyak dan cerahkan",
    key_ingredients: ["Niacinamide 10%", "Moisture Beet", "Hyaluronic Acid"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Bekas jerawat", "Minyak berlebih", "Pori besar", "Kulit kusam"],
    price_min: 55000,
    price_max: 70000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "Konsentrasi niacinamide 10% yang optimal + Moisture Beet (betaine) untuk hidrasi yang tahan lama. Best seller yang teruji.",
    rating_community: 4.7,
  },
  {
    id: "wardah-lightening-serum",
    name: "Lightening Serum",
    brand: "Wardah",
    category: "serum_niacinamide",
    emoji: "✨",
    tagline: "Serum pencerah budget — niacinamide + vitamin C",
    key_ingredients: ["Niacinamide", "Vitamin C Derivative", "Aloe Vera"],
    skin_types: ["normal", "berminyak", "kombinasi"],
    concerns: ["Bekas jerawat", "Kulit kusam", "Hiperpigmentasi ringan"],
    price_min: 30000,
    price_max: 45000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret", "Alfamart", "Guardian"],
    bpom_registered: true,
    why_good: "Pilihan paling terjangkau yang mudah didapat. Cocok untuk yang baru mulai skincare atau yang butuh serum sederhana.",
    rating_community: 4.2,
  },

  // ── SERUM VITAMIN C ──────────────────────────────────────
  {
    id: "skintific-vitamin-c",
    name: "Vitamin C Brightening Serum",
    brand: "Skintific",
    category: "serum_vitamin_c",
    emoji: "🍊",
    tagline: "Vitamin C stabil + niacinamide — cerah tanpa iritasi",
    key_ingredients: ["Ascorbyl Glucoside 3%", "Niacinamide", "Hyaluronic Acid"],
    skin_types: ["semua tipe"],
    concerns: ["Kulit kusam", "Hiperpigmentasi", "Antioksidan pagi"],
    price_min: 60000,
    price_max: 80000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Menggunakan Ascorbyl Glucoside (turunan Vitamin C stabil) yang tidak mudah teroksidasi dan lebih gentle dari L-Ascorbic Acid.",
    rating_community: 4.5,
  },
  {
    id: "azarine-vitamin-c",
    name: "Vitamin C 10% Brightening Serum",
    brand: "Azarine",
    category: "serum_vitamin_c",
    emoji: "🍊",
    tagline: "Vitamin C 10% affordable — pencerah efektif",
    key_ingredients: ["Ascorbic Acid 10%", "Niacinamide", "Hyaluronic Acid"],
    skin_types: ["normal", "berminyak", "kombinasi"],
    concerns: ["Kulit kusam", "Hiperpigmentasi", "Bekas jerawat"],
    price_min: 45000,
    price_max: 60000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Budget-friendly dengan konsentrasi Vitamin C 10% yang efektif. Harus disimpan di tempat gelap dan dingin supaya tidak cepat teroksidasi.",
    rating_community: 4.3,
  },

  // ── SERUM AHA/BHA ──────────────────────────────────────
  {
    id: "somethinc-bha-exfoliant",
    name: "BHA+ Blemish & Blackhead Liquid Exfoliant",
    brand: "Somethinc",
    category: "serum_aha_bha",
    emoji: "🔬",
    tagline: "BHA terbaik lokal — bersihkan pori dan atasi jerawat",
    key_ingredients: ["Salicylic Acid 2%", "Centella Asiatica", "Panthenol"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Komedo", "Jerawat aktif", "Pori besar", "Kulit berminyak"],
    price_min: 60000,
    price_max: 75000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "Salicylic Acid 2% (konsentrasi optimal) dengan Centella untuk menenangkan setelah exfoliant. Tidak terlalu keras untuk pemakaian rutin.",
    who_should_skip: "Kulit sangat sensitif atau kering",
    rating_community: 4.6,
  },
  {
    id: "azarine-aha-toner",
    name: "AHA BHA Clarifying Toner",
    brand: "Azarine",
    category: "serum_aha_bha",
    emoji: "🔬",
    tagline: "Toner exfoliant budget — AHA + BHA untuk kulit bersinar",
    key_ingredients: ["Glycolic Acid", "Salicylic Acid", "Centella Asiatica"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Tekstur kasar", "Kulit kusam", "Jerawat", "Komedo"],
    price_min: 40000,
    price_max: 55000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Kombinasi AHA + BHA dalam satu toner dengan harga sangat terjangkau. Cocok untuk pemula exfoliant.",
    rating_community: 4.4,
  },

  // ── SERUM RETINOL ──────────────────────────────────────
  {
    id: "somethinc-retinol-bakuchiol",
    name: "Bakuchiol + Retinol 0.3% Serum",
    brand: "Somethinc",
    category: "serum_retinol",
    emoji: "🌙",
    tagline: "Retinol 0.3% + Bakuchiol — anti-aging lokal terbaik",
    key_ingredients: ["Retinol 0.3%", "Bakuchiol", "Ceramide", "Peptide"],
    skin_types: ["normal", "kombinasi", "berminyak"],
    concerns: ["Anti-aging", "Tekstur kasar", "Jerawat membandel", "Tanda penuaan"],
    price_min: 80000,
    price_max: 100000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "Kombinasi Retinol + Bakuchiol memberikan efek anti-aging yang lebih kuat dari keduanya sendiri, dengan Ceramide untuk mengurangi iritasi.",
    who_should_skip: "Ibu hamil dan menyusui. Pemula skincare (mulai dari Bakuchiol saja dulu)",
    rating_community: 4.7,
  },
  {
    id: "skintific-retinol",
    name: "Retinol 0.3% Vitamin A Serum",
    brand: "Skintific",
    category: "serum_retinol",
    emoji: "🌙",
    tagline: "Retinol terjangkau dengan formulasi yang kind-to-skin",
    key_ingredients: ["Retinol 0.3%", "Ceramide", "Niacinamide"],
    skin_types: ["normal", "berminyak", "kombinasi"],
    concerns: ["Anti-aging", "Tekstur kulit", "Jerawat"],
    price_min: 70000,
    price_max: 90000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Diimbangi ceramide dan niacinamide untuk mengurangi iritasi khas retinol. Pilihan lokal yang solid.",
    who_should_skip: "Ibu hamil dan menyusui",
    rating_community: 4.5,
  },

  // ── TREATMENT JERAWAT ──────────────────────────────────────
  {
    id: "azarine-azelaic-acid",
    name: "Azelaic Acid 10% Serum",
    brand: "Azarine",
    category: "treatment_jerawat",
    emoji: "⚗️",
    tagline: "Azelaic acid terjangkau — atasi jerawat dan bekas hitam",
    key_ingredients: ["Azelaic Acid 10%", "Niacinamide", "Centella Asiatica"],
    skin_types: ["sensitif", "berminyak", "kombinasi", "normal"],
    concerns: ["Jerawat aktif", "Bekas jerawat", "Rosacea", "Kemerahan"],
    price_min: 45000,
    price_max: 60000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Pilihan terbaik untuk kulit sensitif yang tidak cocok dengan BHA. Aman kehamilan (konsultasi dokter dulu). Multi-fungsi.",
    rating_community: 4.5,
  },
  {
    id: "emina-sunscreen-spf30",
    name: "Sun Protection Moisturizer SPF 30 PA++",
    brand: "Emina",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Sunscreen termudah didapat dengan harga paling terjangkau",
    key_ingredients: ["Ethylhexyl Methoxycinnamate", "Titanium Dioxide"],
    skin_types: ["normal", "kombinasi"],
    concerns: ["UV protection dasar"],
    price_min: 25000,
    price_max: 35000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee", "Tokopedia"],
    spf: 30,
    bpom_registered: true,
    why_good: "Paling mudah ditemukan dan paling murah. Kalau belum punya sunscreen sama sekali, ini adalah titik mulai yang bagus.",
    who_should_skip: "Yang butuh SPF 50+ atau kulit sangat berminyak",
    rating_community: 4.1,
  },

  // ── TREATMENT JERAWAT (tambahan) ──────────────────
  {
    id: "benzolac-gel",
    name: "Benzolac 5% Gel",
    brand: "Benzolac",
    category: "treatment_jerawat",
    emoji: "⚗️",
    tagline: "Benzoyl peroxide lokal — basmi bakteri jerawat dari akar",
    key_ingredients: ["Benzoyl Peroxide 5%"],
    skin_types: ["berminyak", "berjerawat", "kombinasi"],
    concerns: ["Jerawat aktif", "Jerawat meradang", "Jerawat pustula"],
    price_min: 20000,
    price_max: 35000,
    price_range: "budget",
    where_to_buy: ["Apotek", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Benzoyl Peroxide 5% adalah standar emas untuk jerawat meradang. Tersedia di apotek tanpa resep, harga sangat terjangkau.",
    who_should_skip: "Kulit sensitif, bisa menyebabkan iritasi dan pemutihan kain",
    rating_community: 4.3,
  },
  {
    id: "skintific-acne-serum",
    name: "Acne Spot & Serum 2% BHA",
    brand: "Skintific",
    category: "treatment_jerawat",
    emoji: "⚗️",
    tagline: "Dual-action: BHA 2% + niacinamide untuk jerawat dan bekasnya",
    key_ingredients: ["Salicylic Acid 2%", "Niacinamide 10%", "Centella Asiatica"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Jerawat aktif", "Komedo", "Bekas jerawat", "Pori besar"],
    price_min: 65000,
    price_max: 85000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Mengatasi jerawat aktif (BHA) dan bekasnya (niacinamide) dalam satu produk. Efisien untuk yang mau simpel.",
    rating_community: 4.6,
  },
  {
    id: "emina-acne-solution",
    name: "Bright Stuff Acne Solution Serum",
    brand: "Emina",
    category: "treatment_jerawat",
    emoji: "⚗️",
    tagline: "Serum jerawat termurah — untuk pelajar dan mahasiswa",
    key_ingredients: ["Salicylic Acid", "Tea Tree", "Niacinamide"],
    skin_types: ["berminyak", "berjerawat", "kombinasi"],
    concerns: ["Jerawat", "Komedo", "Kulit berminyak"],
    price_min: 25000,
    price_max: 40000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Pilihan paling budget-friendly untuk yang baru mulai skincare anti-jerawat. Mudah ditemukan di minimarket.",
    rating_community: 4.1,
  },

  // ── TONER ──────────────────────────────────────
  {
    id: "somethinc-hyaluronic-toner",
    name: "Hyaluronic Toning Essence",
    brand: "Somethinc",
    category: "toner",
    emoji: "💧",
    tagline: "Toner hidrasi — booster untuk serum dan moisturizer berikutnya",
    key_ingredients: ["Hyaluronic Acid", "Beta-Glucan", "Centella Asiatica"],
    skin_types: ["semua tipe"],
    concerns: ["Kulit kering", "Dehidrasi", "Hidrasi dasar"],
    price_min: 45000,
    price_max: 60000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "Digunakan setelah cuci muka untuk mempersiapkan kulit menyerap produk berikutnya lebih baik. Cocok semua jenis kulit.",
    rating_community: 4.5,
  },
  {
    id: "skintific-toner-cica",
    name: "Centella Calming Toner",
    brand: "Skintific",
    category: "toner",
    emoji: "💧",
    tagline: "Toner Cica — tenangkan setelah cleansing dan persiapkan serum",
    key_ingredients: ["Centella Asiatica", "Aloe Vera", "Panthenol"],
    skin_types: ["sensitif", "kering", "normal", "kombinasi"],
    concerns: ["Kemerahan", "Kulit sensitif", "Iritasi"],
    price_min: 50000,
    price_max: 65000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Centella membantu calming setelah cuci muka, sangat cocok untuk kulit reaktif atau yang sedang recovery.",
    rating_community: 4.4,
  },

  // ── MOISTURIZER (tambahan) ──────────────────────
  {
    id: "wardah-aloe-vera-gel",
    name: "Aloe Vera Gel",
    brand: "Wardah",
    category: "moisturizer",
    emoji: "🌿",
    tagline: "Gel aloe vera serbaguna — moisturizer, masker, after-sun",
    key_ingredients: ["Aloe Vera 98%", "Allantoin", "Panthenol"],
    skin_types: ["berminyak", "kombinasi", "sensitif", "semua tipe"],
    concerns: ["Kulit berminyak", "Kemerahan", "After-sun care"],
    price_min: 25000,
    price_max: 40000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret", "Alfamart", "Guardian"],
    bpom_registered: true,
    why_good: "Paling serbaguna. Bisa sebagai moisturizer ringan, masker, atau meredakan kulit kemerahan. Non-komedogenik, cocok kulit berminyak.",
    rating_community: 4.4,
  },
  {
    id: "npure-cica-moisturizer",
    name: "Centella Asiatica Balancing Emulsion",
    brand: "NPURE",
    category: "moisturizer",
    emoji: "🌿",
    tagline: "Emulsi ringan Cica — balance dan tenangkan kulit sensitif",
    key_ingredients: ["Centella Asiatica", "Ceramide", "Allantoin"],
    skin_types: ["sensitif", "normal", "kombinasi"],
    concerns: ["Kulit sensitif", "Kemerahan", "Skin barrier lemah"],
    price_min: 45000,
    price_max: 65000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Indomaret"],
    bpom_registered: true,
    why_good: "Tekstur emulsi ringan yang tidak menyumbat pori. Kombinasi Cica + Ceramide memperbaiki barrier sambil menenangkan.",
    rating_community: 4.3,
  },

  // ── SERUM NIACINAMIDE (tambahan) ────────────────
  {
    id: "skintific-niacinamide-serum",
    name: "Mugwort + Niacinamide Pore Serum",
    brand: "Skintific",
    category: "serum_niacinamide",
    emoji: "✨",
    tagline: "Niacinamide + Mugwort — kontrol pori dan minyak lebih kuat",
    key_ingredients: ["Niacinamide 10%", "Mugwort Extract", "Hyaluronic Acid"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Pori besar", "Minyak berlebih", "Bekas jerawat", "Komedo"],
    price_min: 60000,
    price_max: 78000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    why_good: "Mugwort ekstrak membantu menenangkan dan mengontrol sebum secara sinergis dengan niacinamide. Formula paling solid untuk pori besar.",
    rating_community: 4.6,
  },

  // ── SERUM PENCERAH (brightening) ────────────────
  {
    id: "azarine-alpha-arbutin",
    name: "Alpha Arbutin 2% + Kojic Acid Serum",
    brand: "Azarine",
    category: "serum_brightening",
    emoji: "🌟",
    tagline: "Alpha arbutin + kojic acid — cerahkan bekas jerawat dan flek hitam",
    key_ingredients: ["Alpha Arbutin 2%", "Kojic Acid", "Niacinamide"],
    skin_types: ["semua tipe"],
    concerns: ["Bekas jerawat", "Flek hitam", "Hiperpigmentasi", "Kulit kusam"],
    price_min: 40000,
    price_max: 55000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Kombinasi dua bahan pencerah terbukti ilmiah. Alpha Arbutin menghambat melanin, Kojic Acid memperkuat efeknya. Budget terjangkau.",
    rating_community: 4.4,
  },
  {
    id: "somethinc-tranexamic-acid",
    name: "Trixylane + Tranexamic Acid Brightening Serum",
    brand: "Somethinc",
    category: "serum_brightening",
    emoji: "🌟",
    tagline: "Tranexamic Acid — pencerah terkuat yang aman sensitif",
    key_ingredients: ["Tranexamic Acid 5%", "Trixylane", "Hyaluronic Acid"],
    skin_types: ["sensitif", "kering", "normal", "kombinasi"],
    concerns: ["Bekas jerawat membandel", "Melasma", "Flek hitam dalam", "Hiperpigmentasi"],
    price_min: 90000,
    price_max: 120000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Store"],
    bpom_registered: true,
    why_good: "Tranexamic Acid dianggap lebih efektif dari niacinamide untuk hiperpigmentasi dalam, dan lebih gentle dari AHA. Pilihan premium yang worth it.",
    rating_community: 4.8,
  },

  // ── CLEANSER (tambahan) ─────────────────────────
  {
    id: "cerave-hydrating-cleanser",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    category: "cleanser",
    emoji: "🧴",
    tagline: "Cleanser dokter kulit — melembapkan sambil membersihkan",
    key_ingredients: ["Ceramide 1,3,6-II", "Hyaluronic Acid", "Glycerin"],
    skin_types: ["kering", "normal", "sensitif"],
    concerns: ["Kulit kering", "Skin barrier lemah", "Kulit sensitif"],
    price_min: 85000,
    price_max: 130000,
    price_range: "mid",
    where_to_buy: ["Guardian", "Watsons", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Formula non-stripping yang menjaga kelembapan. Direkomendasikan dermatologis untuk kulit kering dan sensitif. Tidak mengganggu skin barrier.",
    who_should_skip: "Kulit sangat berminyak — teksturnya lebih creamy, bisa terasa berat",
    rating_community: 4.7,
  },
  {
    id: "garnier-micellar-water",
    name: "Micellar Cleansing Water All-in-1",
    brand: "Garnier",
    category: "cleanser",
    emoji: "🧴",
    tagline: "Micellar water paling terjangkau — bersihkan makeup tanpa dibilas",
    key_ingredients: ["Micelles", "Rose Water", "Glycerin"],
    skin_types: ["semua tipe"],
    concerns: ["Pembersih makeup", "Double cleansing step 1", "Kulit sensitif"],
    price_min: 25000,
    price_max: 45000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Guardian", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Pilihan terbaik untuk first cleanser di double cleansing. Lembut, tidak perlu dibilas, sangat cocok sebagai pengganti cleansing oil budget.",
    rating_community: 4.4,
  },

  // ── SUNSCREEN (tambahan) ────────────────────────
  {
    id: "isntree-hyaluronic-acid-sun-gel",
    name: "Hyaluronic Acid Watery Sun Gel SPF 50+ PA++++",
    brand: "Isntree",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Sunscreen Korea terbaik — ringan, lembap, no white cast sama sekali",
    key_ingredients: ["Hyaluronic Acid", "Zinc Oxide", "Niacinamide"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["UV protection", "Kulit berminyak", "No white cast"],
    price_min: 90000,
    price_max: 140000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Althea"],
    spf: 50,
    bpom_registered: true,
    why_good: "Tekstur gel paling ringan di kelasnya. Zero white cast. Finishing matte yang sempurna untuk kulit berminyak. Sangat populer di kalangan skincare enthusiast Indonesia.",
    rating_community: 4.8,
  },
  {
    id: "skintific-uv-moist-spf50",
    name: "Multi-Protection UV Moist Sunscreen SPF 50 PA++++",
    brand: "Skintific",
    category: "sunscreen",
    emoji: "☀️",
    tagline: "Sunscreen + moisturizer dalam satu — dua langkah jadi satu",
    key_ingredients: ["Zinc Oxide", "Tinosorb M", "Ceramide", "Hyaluronic Acid"],
    skin_types: ["kering", "normal", "kombinasi"],
    concerns: ["UV protection", "Kulit kering", "Efisiensi rutinitas"],
    price_min: 70000,
    price_max: 90000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    spf: 50,
    bpom_registered: true,
    why_good: "Menggabungkan moisturizer dan sunscreen SPF 50 PA++++. Hemat langkah dan waktu, cocok untuk yang suka rutinitas simpel.",
    rating_community: 4.6,
  },

  // ── TONER (tambahan) ────────────────────────────
  {
    id: "some-by-mi-aha-bha-pha",
    name: "AHA BHA PHA 30 Days Miracle Toner",
    brand: "Some By Mi",
    category: "toner",
    emoji: "💧",
    tagline: "Triple acid toner — eksfoliasi dan bersihkan pori dalam 30 hari",
    key_ingredients: ["AHA (Glycolic Acid)", "BHA (Salicylic Acid)", "PHA", "Tea Tree", "Niacinamide"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Jerawat", "Pori besar", "Komedo", "Kulit kusam"],
    price_min: 85000,
    price_max: 120000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Althea", "Guardian"],
    bpom_registered: true,
    why_good: "Triple acid (AHA+BHA+PHA) dalam satu toner yang efektif untuk eksfoliasi, membersihkan pori, dan mengatasi jerawat. Best seller Korea.",
    who_should_skip: "Kulit kering atau sensitif — formula acid-heavy bisa terlalu keras",
    rating_community: 4.5,
  },
  {
    id: "cosrx-snail-mucin-essence",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "Cosrx",
    category: "toner",
    emoji: "🐌",
    tagline: "Snail mucin — soothing, hidrasi, dan perbaikan kulit dalam satu produk",
    key_ingredients: ["Snail Secretion Filtrate 96%", "Sodium Hyaluronate"],
    skin_types: ["semua tipe", "sensitif", "kering"],
    concerns: ["Kulit sensitif", "Regenerasi kulit", "Hidrasi", "Kemerahan"],
    price_min: 120000,
    price_max: 170000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Althea"],
    bpom_registered: true,
    why_good: "Snail mucin 96% adalah humektan dan soothing agent sekaligus. Membantu mempercepat perbaikan kulit, cocok setelah treatment aktif.",
    rating_community: 4.7,
  },

  // ── SERUM RETINOL (tambahan) ────────────────────
  {
    id: "avoskin-retinol",
    name: "Your Skin Bae Retinol 0.1% + Bakuchiol",
    brand: "Avoskin",
    category: "serum_retinol",
    emoji: "⭐",
    tagline: "Retinol lokal terbaik — buffered formula agar tidak iritasi",
    key_ingredients: ["Retinol 0.1%", "Bakuchiol", "Allantoin", "Niacinamide"],
    skin_types: ["semua tipe", "normal", "kombinasi"],
    concerns: ["Anti-aging", "Bekas jerawat", "Tekstur kulit", "Garis halus"],
    price_min: 119000,
    price_max: 150000,
    price_range: "mid",
    where_to_buy: ["Avoskin Official", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Formula retinol yang dibuffer dengan Bakuchiol dan Allantoin — mengurangi iritasi sambil tetap efektif. Konsentrasi 0.1% ideal untuk pemula retinol.",
    who_should_skip: "Ibu hamil/menyusui — kandungan retinol tidak dianjurkan",
    rating_community: 4.7,
  },

  // ── SERUM VITAMIN C (tambahan) ──────────────────
  {
    id: "klairs-vitamin-c",
    name: "Freshly Juiced Vitamin Drop 5%",
    brand: "Klairs",
    category: "serum_vitamin_c",
    emoji: "🍊",
    tagline: "Vitamin C 5% yang tidak bikin perih — aman untuk kulit sensitif",
    key_ingredients: ["Ascorbic Acid 5%", "Adenosine", "Niacinamide"],
    skin_types: ["sensitif", "kering", "normal"],
    concerns: ["Pencerah", "Anti-aging ringan", "Kulit sensitif", "Warna kulit tidak merata"],
    price_min: 170000,
    price_max: 230000,
    price_range: "premium",
    where_to_buy: ["Shopee", "Tokopedia", "Althea", "Watsons"],
    bpom_registered: true,
    why_good: "Konsentrasi 5% vitamin C murni yang lebih lembut dari 10-20%. Cocok untuk yang ingin memulai vitamin C tanpa risiko perih dan iritasi.",
    rating_community: 4.6,
  },

  // ── MOISTURIZER (tambahan) ──────────────────────
  {
    id: "erha-day-moisturizer",
    name: "Erha 21 Daily Moisturizer",
    brand: "Erha",
    category: "moisturizer",
    emoji: "🌿",
    tagline: "Moisturizer dermatologis lokal — lembap tanpa berminyak",
    key_ingredients: ["Ceramide", "Niacinamide", "Panthenol", "Allantoin"],
    skin_types: ["semua tipe", "berjerawat", "sensitif"],
    concerns: ["Hidrasi sehari-hari", "Skin barrier", "Kulit bermasalah"],
    price_min: 65000,
    price_max: 95000,
    price_range: "mid",
    where_to_buy: ["Erha Clinic", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Diformulasikan oleh dermatolog Indonesia. Ringan, tidak comedogenic, cocok bahkan untuk kulit jerawatan. Formula derma-grade dengan harga terjangkau.",
    rating_community: 4.5,
  },

  // ══════════════════════════════════════════════════
  // HANASUI
  // ══════════════════════════════════════════════════
  {
    id: "hanasui-niacinamide-tonepad",
    name: "Niacinamide + Moisture Tonepad",
    brand: "Hanasui",
    category: "toner",
    emoji: "🌸",
    tagline: "Toner pad niacinamide — cerahkan pori dan kontrol minyak dalam sekali usap",
    key_ingredients: ["Niacinamide 5%", "Hyaluronic Acid", "Centella Asiatica"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Pori besar", "Minyak berlebih", "Warna kulit tidak merata"],
    price_min: 25000,
    price_max: 40000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Niacinamide 5% dalam format tonepad yang praktis dan sangat terjangkau. Cocok untuk pemula yang ingin mulai dengan niacinamide tanpa risiko.",
    rating_community: 4.3,
  },
  {
    id: "hanasui-vitamin-c-serum",
    name: "Vitamin C Brightening Serum",
    brand: "Hanasui",
    category: "serum_vitamin_c",
    emoji: "🍋",
    tagline: "Vitamin C paling terjangkau — pencerah kulit kusam untuk pemula",
    key_ingredients: ["Vitamin C (Ascorbic Acid)", "Niacinamide", "Hyaluronic Acid"],
    skin_types: ["semua tipe"],
    concerns: ["Kulit kusam", "Bekas jerawat", "Pencerah"],
    price_min: 20000,
    price_max: 35000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Entry-level vitamin C dengan harga paling ramah di kantong. Formulanya lebih stabil dari serum vitamin C murni konsentrasi tinggi — cocok banget untuk pemula.",
    rating_community: 4.1,
  },
  {
    id: "hanasui-acne-clay-mask",
    name: "Acne Care Clay Mask",
    brand: "Hanasui",
    category: "treatment_jerawat",
    emoji: "🌿",
    tagline: "Clay mask lokal murah — serap minyak dan bersihkan pori kotor",
    key_ingredients: ["Kaolin Clay", "Salicylic Acid", "Tea Tree"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Pori tersumbat", "Jerawat aktif", "Minyak berlebih"],
    price_min: 18000,
    price_max: 30000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee"],
    bpom_registered: true,
    why_good: "Clay mask dengan salicylic acid di harga di bawah Rp 30k. Pakai 2x seminggu untuk kontrol komedo dan minyak berlebih — efektif dan tidak perlu mahal.",
    rating_community: 4.0,
  },

  // ══════════════════════════════════════════════════
  // SCARLETT WHITENING
  // ══════════════════════════════════════════════════
  {
    id: "scarlett-brightly-serum",
    name: "Brightly Serum",
    brand: "Scarlett Whitening",
    category: "serum_brightening",
    emoji: "✨",
    tagline: "Vitamin C + Niacinamide — combo pencerah terpopuler di Indonesia",
    key_ingredients: ["Vitamin C", "Niacinamide", "Alpha Arbutin", "Kojic Acid"],
    skin_types: ["semua tipe"],
    concerns: ["Hiperpigmentasi", "Bekas jerawat", "Kulit kusam", "Flek hitam"],
    price_min: 55000,
    price_max: 75000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Scarlett Official", "TikTok Shop"],
    bpom_registered: true,
    why_good: "Kombinasi brightening agent paling lengkap di harga budget: vitamin C, niacinamide, alpha arbutin, dan kojic acid dalam satu botol. Salah satu bestseller lokal.",
    rating_community: 4.4,
  },
  {
    id: "scarlett-acne-serum",
    name: "Acne Serum",
    brand: "Scarlett Whitening",
    category: "treatment_jerawat",
    emoji: "💊",
    tagline: "Salicylic acid + niacinamide — treatment jerawat yang terbukti efektif",
    key_ingredients: ["Salicylic Acid 0.5%", "Niacinamide", "Centella Asiatica", "Tea Tree"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Jerawat aktif", "Komedo", "Pori besar", "Bekas jerawat"],
    price_min: 50000,
    price_max: 70000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "Scarlett Official", "TikTok Shop"],
    bpom_registered: true,
    who_should_skip: "Kulit sangat sensitif atau kering — bisa bikin over-dry",
    why_good: "BHA + centella asiatica adalah kombinasi treatment jerawat yang ideal: BHA eksfoliasi dalam pori, centella menenangkan inflamasi. Harga sangat terjangkau.",
    rating_community: 4.3,
  },

  // ══════════════════════════════════════════════════
  // BLP BEAUTY
  // ══════════════════════════════════════════════════
  {
    id: "blp-skin-prep-serum",
    name: "Skin Prep Serum",
    brand: "BLP Beauty",
    category: "serum_niacinamide",
    emoji: "💧",
    tagline: "Prep serum hidrasi — kulit lembap, plump, dan siap menerima produk lain",
    key_ingredients: ["Hyaluronic Acid", "Niacinamide", "Beta-Glucan", "Panthenol"],
    skin_types: ["semua tipe", "kering", "sensitif"],
    concerns: ["Dehidrasi", "Kulit kusam", "Skin barrier lemah", "Tekstur kasar"],
    price_min: 115000,
    price_max: 145000,
    price_range: "mid",
    where_to_buy: ["BLP Official", "Shopee", "Tokopedia", "Sociolla"],
    bpom_registered: true,
    why_good: "Formula minimalis dengan bahan-bahan terbukti: HA, beta-glucan, dan panthenol. Tekstur ringan yang layering-friendly, cocok dipakai sebelum serum aktif.",
    rating_community: 4.5,
  },
  {
    id: "blp-face-mist",
    name: "Hydrating Face Mist",
    brand: "BLP Beauty",
    category: "toner",
    emoji: "💨",
    tagline: "Mist serbaguna — refresh kulitmu di tengah hari atau sebagai toner",
    key_ingredients: ["Hyaluronic Acid", "Rose Water", "Glycerin", "Niacinamide"],
    skin_types: ["semua tipe"],
    concerns: ["Dehidrasi", "Kulit kusam", "Refresh instan"],
    price_min: 85000,
    price_max: 115000,
    price_range: "mid",
    where_to_buy: ["BLP Official", "Shopee", "Tokopedia", "Sociolla"],
    bpom_registered: true,
    why_good: "Bisa dipakai 3 cara: sebagai toner setelah cleansing, sebelum moisturizer, atau refresh di siang hari. Multi-fungsi dan travel-friendly.",
    rating_community: 4.4,
  },

  // ══════════════════════════════════════════════════
  // MS GLOW
  // ══════════════════════════════════════════════════
  {
    id: "msglow-acne-serum",
    name: "Acne Serum",
    brand: "Ms Glow",
    category: "treatment_jerawat",
    emoji: "🎯",
    tagline: "Treatment jerawat lokal — salicylic acid untuk kontrol breakout",
    key_ingredients: ["Salicylic Acid", "Niacinamide", "Tea Tree Oil", "Allantoin"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Jerawat aktif", "Komedo", "Pori besar"],
    price_min: 75000,
    price_max: 110000,
    price_range: "mid",
    where_to_buy: ["Ms Glow Official", "Shopee", "Tokopedia", "TikTok Shop"],
    bpom_registered: true,
    why_good: "Kombinasi salicylic acid dan tea tree yang dikenal efektif untuk jerawat, dipadukan allantoin untuk meminimalkan iritasi. Brand lokal dengan distribusi luas.",
    rating_community: 4.2,
  },
  {
    id: "msglow-brightening-moisturizer",
    name: "Brightening Moisturizer",
    brand: "Ms Glow",
    category: "moisturizer",
    emoji: "🌟",
    tagline: "Moisturizer pencerah dari brand lokal terpopuler Indonesia",
    key_ingredients: ["Niacinamide", "Alpha Arbutin", "Hyaluronic Acid", "Vitamin E"],
    skin_types: ["normal", "kombinasi", "berminyak"],
    concerns: ["Kulit kusam", "Hiperpigmentasi", "Hidrasi", "Warna kulit tidak merata"],
    price_min: 80000,
    price_max: 120000,
    price_range: "mid",
    where_to_buy: ["Ms Glow Official", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Moisturizer 2-in-1 yang melembapkan sekaligus mencerahkan. Tekstur ringan yang tidak berat di kulit berminyak, dengan niacinamide dan alpha arbutin.",
    rating_community: 4.1,
  },

  // ══════════════════════════════════════════════════
  // PIXY
  // ══════════════════════════════════════════════════
  {
    id: "pixy-make-it-glow-serum",
    name: "Make It Glow Brightening Serum",
    brand: "Pixy",
    category: "serum_brightening",
    emoji: "⭐",
    tagline: "Serum pencerah drugstore — harga minimarket, hasil nyata",
    key_ingredients: ["Vitamin C", "Niacinamide", "Hyaluronic Acid"],
    skin_types: ["semua tipe"],
    concerns: ["Kulit kusam", "Bekas jerawat", "Pencerah"],
    price_min: 30000,
    price_max: 50000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Alfamart", "Shopee", "Tokopedia", "Guardian"],
    bpom_registered: true,
    why_good: "Serum pencerah drugstore paling mudah ditemukan — bisa dibeli di minimarket terdekat. Formulanya sederhana tapi efektif untuk kulit kusam.",
    rating_community: 4.0,
  },

  // ══════════════════════════════════════════════════
  // THE ORIGINOTE
  // ══════════════════════════════════════════════════
  {
    id: "originote-ceramide-moisturizer",
    name: "Ceramide Moisturizer",
    brand: "The Originote",
    category: "moisturizer",
    emoji: "🛡️",
    tagline: "Ceramide + hyaluronic acid — perbaiki skin barrier di harga budget",
    key_ingredients: ["Ceramide NP", "Hyaluronic Acid", "Niacinamide", "Panthenol"],
    skin_types: ["semua tipe", "sensitif", "kering"],
    concerns: ["Skin barrier rusak", "Kulit kering", "Kemerahan", "Sensitif"],
    price_min: 35000,
    price_max: 55000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "TikTok Shop"],
    bpom_registered: true,
    why_good: "Ceramide moisturizer di harga budget yang langka. Formula mirip produk premium tapi seperenam harganya. Cocok untuk barrier repair routine.",
    rating_community: 4.5,
  },
  {
    id: "originote-hyaluronic-toner",
    name: "Hyaluronic Acid Toner",
    brand: "The Originote",
    category: "toner",
    emoji: "💧",
    tagline: "Toner HA murni — hidrasi maksimal sebelum serum dan moisturizer",
    key_ingredients: ["Hyaluronic Acid (3 berat molekul)", "Beta-Glucan", "Centella Asiatica"],
    skin_types: ["semua tipe", "kering", "sensitif"],
    concerns: ["Dehidrasi", "Kulit kering", "Skin barrier lemah"],
    price_min: 30000,
    price_max: 48000,
    price_range: "budget",
    where_to_buy: ["Shopee", "Tokopedia", "TikTok Shop"],
    bpom_registered: true,
    why_good: "3 ukuran molekul HA berbeda menembus kulit di lapisan berbeda untuk hidrasi lebih merata. Formula minimalis tanpa fragrance, aman untuk sensitif.",
    rating_community: 4.4,
  },

  // ══════════════════════════════════════════════════
  // SOMETHINC (tambahan)
  // ══════════════════════════════════════════════════
  {
    id: "somethinc-hyaluronic-serum",
    name: "Hyaluronic Acid + B5 Serum",
    brand: "Somethinc",
    category: "serum_niacinamide",
    emoji: "🫧",
    tagline: "HA + B5 — duo hidrasi terbaik untuk kulit kering dan dehidrasi",
    key_ingredients: ["Hyaluronic Acid", "Panthenol (B5)", "Glycerin"],
    skin_types: ["kering", "sensitif", "normal", "kombinasi"],
    concerns: ["Dehidrasi", "Kulit kering", "Skin barrier", "Kemerahan"],
    price_min: 75000,
    price_max: 110000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Official", "Sociolla"],
    bpom_registered: true,
    why_good: "Hyaluronic acid + panthenol (B5) adalah kombinasi hidrasi paling efektif: HA menarik air dari udara, B5 membantu barrier kulit menahannya.",
    rating_community: 4.6,
  },
  {
    id: "somethinc-aha-bha-toner",
    name: "AHA BHA PHA Clarifying Toner",
    brand: "Somethinc",
    category: "serum_aha_bha",
    emoji: "⚗️",
    tagline: "Triple exfoliant toner — eksfoliasi menyeluruh untuk kulit lebih cerah",
    key_ingredients: ["Glycolic Acid (AHA)", "Salicylic Acid (BHA)", "PHA", "Niacinamide"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Tekstur kasar", "Kulit kusam", "Komedo", "Bekas jerawat"],
    price_min: 85000,
    price_max: 120000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Somethinc Official", "Sociolla"],
    bpom_registered: true,
    who_should_skip: "Kulit kering atau sensitif — mulai 1x seminggu",
    why_good: "Kombinasi AHA+BHA+PHA mengatasi masalah dari berbagai sudut: AHA eksfoliasi permukaan, BHA masuk pori, PHA lebih lembut untuk sensitif. Toner exfoliant terbaik di kelasnya.",
    rating_community: 4.5,
  },

  // ══════════════════════════════════════════════════
  // AVOSKIN (tambahan)
  // ══════════════════════════════════════════════════
  {
    id: "avoskin-miraculous-toner",
    name: "Miraculous Refining Toner AHA BHA PHA",
    brand: "Avoskin",
    category: "serum_aha_bha",
    emoji: "🧪",
    tagline: "AHA BHA PHA toner premium lokal — eksfoliasi gentle dan efektif",
    key_ingredients: ["Glycolic Acid", "Salicylic Acid", "PHA", "Hyaluronic Acid", "Niacinamide"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Tekstur kulit", "Komedo", "Kulit kusam", "Bekas jerawat"],
    price_min: 110000,
    price_max: 155000,
    price_range: "mid",
    where_to_buy: ["Avoskin Official", "Shopee", "Tokopedia", "Sociolla"],
    bpom_registered: true,
    who_should_skip: "Pemula wajib mulai 1x seminggu. Sensitif hindari.",
    why_good: "Versi premium dari triple exfoliant toner lokal, dengan tambahan HA untuk minimalisir over-drying. Salah satu cult-product skincare lokal Indonesia.",
    rating_community: 4.7,
  },

  // ══════════════════════════════════════════════════
  // WARDAH (tambahan)
  // ══════════════════════════════════════════════════
  {
    id: "wardah-acne-solution-serum",
    name: "Acne Solution Active Spot Gel",
    brand: "Wardah",
    category: "treatment_jerawat",
    emoji: "💊",
    tagline: "Spot treatment jerawat Wardah — langsung kena targetnya",
    key_ingredients: ["Salicylic Acid 0.5%", "Niacinamide", "Centella Asiatica", "Allantoin"],
    skin_types: ["berminyak", "kombinasi", "berjerawat"],
    concerns: ["Jerawat aktif", "Spot treatment", "Kemerahan"],
    price_min: 25000,
    price_max: 40000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Guardian", "Watsons", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Spot treatment untuk jerawat aktif yang mudah ditemukan di mana saja. BHA langsung ke titik jerawat dengan allantoin agar tidak terlalu kering.",
    rating_community: 4.2,
  },
  {
    id: "wardah-hydrating-toner",
    name: "White Secret Brightening Toner",
    brand: "Wardah",
    category: "toner",
    emoji: "🌼",
    tagline: "Toner pencerah Wardah — hydrating sekaligus menyamarkan kulit kusam",
    key_ingredients: ["Niacinamide", "Vitamin C", "Hyaluronic Acid"],
    skin_types: ["normal", "kombinasi", "kering"],
    concerns: ["Kulit kusam", "Hidrasi ringan", "Pencerah"],
    price_min: 30000,
    price_max: 50000,
    price_range: "budget",
    where_to_buy: ["Indomaret", "Guardian", "Watsons", "Shopee", "Tokopedia"],
    bpom_registered: true,
    why_good: "Toner lokal paling mudah ditemukan di mana saja. Formulanya ringan dan menyegarkan — cocok sebagai first toner untuk pemula yang baru mulai skincare.",
    rating_community: 4.1,
  },

  // ══════════════════════════════════════════════════
  // SKINTIFIC (tambahan)
  // ══════════════════════════════════════════════════
  {
    id: "skintific-salicylic-acid-toner",
    name: "AHA BHA Salicylic Acid Daily Toner",
    brand: "Skintific",
    category: "serum_aha_bha",
    emoji: "🔬",
    tagline: "Daily exfoliant toner Skintific — bersihkan pori tanpa iritasi berlebih",
    key_ingredients: ["Salicylic Acid (BHA)", "Glycolic Acid (AHA)", "Niacinamide", "Centella"],
    skin_types: ["berminyak", "kombinasi", "normal"],
    concerns: ["Komedo", "Pori besar", "Kulit kusam", "Jerawat"],
    price_min: 65000,
    price_max: 90000,
    price_range: "mid",
    where_to_buy: ["Shopee", "Tokopedia", "Skintific Store"],
    bpom_registered: true,
    who_should_skip: "Kulit sangat sensitif atau kering — mulai 2x seminggu",
    why_good: "Exfoliant toner dari Skintific yang sudah terbukti: formula dual-exfoliant dengan centella untuk menenangkan. Lebih gentle dari toner exfoliant lain di kelasnya.",
    rating_community: 4.5,
  },
];

export function getProductsByCategory(category: ProductCategory): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsBySkinType(skinType: string): Product[] {
  return PRODUCTS.filter((p) =>
    p.skin_types.includes(skinType as SkinTypeMatch) || p.skin_types.includes("semua tipe")
  );
}

export function getProductsByBudget(maxPrice: number): Product[] {
  return PRODUCTS.filter((p) => p.price_min <= maxPrice);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.key_ingredients.some((i) => i.toLowerCase().includes(q)) ||
      p.concerns.some((c) => c.toLowerCase().includes(q))
  );
}

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  sunscreen: "Sunscreen",
  cleanser: "Cleanser",
  moisturizer: "Moisturizer",
  serum_niacinamide: "Serum Niacinamide",
  serum_vitamin_c: "Serum Vitamin C",
  serum_aha_bha: "Serum AHA/BHA",
  serum_retinol: "Serum Retinol",
  serum_brightening: "Serum Pencerah",
  toner: "Toner",
  treatment_jerawat: "Treatment Jerawat",
};
